### ISSUE TITLE
Restyling multiline function definitions double indents `) {`

### ISSUE THREAD

**Issue by rossellhayes** [gadenbuie/grkstyle#10]
When styling a multiline function definition, `grkstyle` adds a double indent before the `) {` line that separates arguments from the function body.

This happens whether using tabs or spaces for indentation.

``` r
tempfile <- fs::path_ext_set(tempfile(), "R")

writeLines("
x <- function(
  a = 1,
  b = 2
) {
  a + b
}",
  tempfile
)

options(grkstyle.use_tabs = FALSE)
grkstyle::grk_style_file(tempfile)
#> Styling  1  files:
#>  /var/folders/z9/75xbv79s5cq8lbfkg3ppsxpw0000gn/T/RtmpmvIKt1/file136c3d019583.R ℹ 
#> ──────────────────────────────────────────────────────────────────────────────
#> Status   Count   Legend 
#> ✔    0   File unchanged.
#> ℹ    1   File changed.
#> ✖    0   Styling threw an error.
#> ──────────────────────────────────────────────────────────────────────────────
#> Please review the changes carefully!
cat(readLines(tempfile), sep = "\n")
#> x <- function(
#>   a = 1,
#>   b = 2
#>     ) {
#>   a + b
#> }

options(grkstyle.use_tabs = TRUE)
grkstyle::grk_style_file(tempfile)
#> Styling  1  files:
#>  /var/folders/z9/75xbv79s5cq8lbfkg3ppsxpw0000gn/T/RtmpmvIKt1/file136c3d019583.R ℹ 
#> ──────────────────────────────────────────────────────────────────────────────
#> Status   Count   Legend 
#> ✔    0   File unchanged.
#> ℹ    1   File changed.
#> ✖    0   Styling threw an error.
#> ──────────────────────────────────────────────────────────────────────────────
#> Please review the changes carefully!
cat(readLines(tempfile), sep = "\n")
#> x <- function(
#>  a = 1,
#>  b = 2
#>              ) {
#>  a + b
#> }
```

<sup>Created on 2023-03-23 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by gadenbuie** [comment]
This seems like a new thing, right? I wonder if something changed in styler

**Comment by rossellhayes** [comment]
I think that's right, it looks like it might be coming from these lines, updated 3 months ago:
https://github.com/r-lib/styler/blame/57bbf4e54af3f9aedbcb5f0e2353ae1b19d1b30c/R/rules-indention.R#L25-L26

**Comment by tjmahr** [comment]
The tidyverse style guide now likes double-indented arguments in multiline function definitions. https://style.tidyverse.org/functions.html

```
long_function_name <- function(
    a = "a long argument",
    b = "another argument",
    c = "another long argument") {
  # As usual code is indented by two spaces.
}
```

So I think some wires are getting crossed.

**Comment by gadenbuie** [comment]
@tjmahr Does this still happen for you? I haven't run into personally and I use grkstyle daily. I can say this would annoy me to no end so I'm motivated to fix it if it is a problem.

**Comment by gadenbuie** [comment]
oh crap, I tried @rossellhayes's reprex right now and it reproduces every time. ugh. I'll see what I can do 😄

**Comment by tjmahr** [comment]
I don't use styler often but have `options(styler.addins_style_transformer = "grkstyle::grk_style_transformer()")` in all my project .Rprofiles. Just tried it and it happened for me.

**Comment by KoderKow** [comment]
Is there a workaround for this? My linting checks are getting upset about the double indents. I am using the latest {grkstyle} and {styler} packages.

I have a small package where I am using this to ignore the lines:

```r
f <- function(
  x = "",
  y = 2
) { # styler: off
  ...
}
```

However, for other projects with 100+ functions this can become a bit tedious. 

Appreciate the fantastic work and help!

**Comment by gadenbuie** [comment]
Thanks for the nudge @KoderKow and to @rossellhayes for pointing me to the place where the implementation changed. I figured out how to work around the new behavior and I think it's done in a way that's going to work out well (but you should always have a stashed or committed version before you apply styler or grkstyle).

If you run into an other weirdness around functions, please open a new issue with examples so I can take a look!
