### ISSUE TITLE
Function indentation - comments

### ISSUE THREAD

**Issue by JohnCoene** [gadenbuie/grkstyle#11]
Hi Garrick!

Thank you for this, love the style.

I just encounter an issue with function indentation and comments.

This function is formatted correctly but lintr raises a warning because of the name (`...`)

```r
...foo <- function(
  one,
  two,
  three
){
  # do something
}
```

I want to get rid of the lintr warning with the comment, which works

```r
...foo <- function( # nolint
  one,
  two,
  three
){
  # do something
}
```

But on save grkstyle restyles it to:

```r
...foo <- function( 
  # nolint
  one,
  two,
  three
){
  # do something
}
```

which raises the warning from lintr again

**Comment by gadenbuie** [comment]
Argh! But also you're just in time, I just saw that a new release of lintr just landed on CRAN and [it now supports `# nolint next`](https://github.com/r-lib/lintr/issues/1791), so you can do this for now:

```r
# nolint next
...foo <- function( 
  one,
  two,
  three
){
  # do something
}
```

**Comment by JohnCoene** [comment]
Ah great thank you!

**Comment by JohnCoene** [comment]
Sorry Garrick, I think I had my editor config wrong, it was not caused by your package.

**Comment by gadenbuie** [comment]
No worries, this is great news for me! 😄
